// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  introSidebar: [{type: 'autogenerated', dirName: '01_intro'}],
  actionsSidebar: [{type: 'autogenerated', dirName: '02_actions'}],
  lifecycleNodesSidebar: [{type: 'autogenerated', dirName: '03_lifecycle_nodes'}],
  executorsSidebar: [{type: 'autogenerated', dirName: '04_executors'}],
  componentsSidebar: [{type: 'autogenerated', dirName: '05_components'}],
};

export default sidebars;
